scalar DateTime
scalar Date
scalar BigDecimal

interface Node {
    id: ID!
    createdAt: DateTime!
    updatedAt: DateTime!
}

input Map{
    key : String
    value : String
}


type PageInfo{
    hasNextPage: Boolean!
    hasPreviousPage: Boolean!
    startCursor: String
    endCursor: String
}

type ErrorStack{
    field : String!
    message :  String!
}

type ErrorResponse{
    status : Int!
    message : String!
    errorStack : ErrorStack
}

enum MilkType{
    COW,BUFFALO
}

enum UserRole{
    ADMIN,CUSTOMER,VENDOR
}

enum BillingCycle{
    DAILY,
    WEEKLY,
    MONTHLY,
}

enum PaymentStatus{
    PENDING,
    HALF_PAID
    PAID
}

enum OrderStatus{
    PENDING,SHIPPED,DELIVERED,CANCELED
}

enum AccountStatus{
    ACTIVE,INACTIVE,SUSPEND
}

enum DeliverySession{
    MORNING,
    EVENING,
    BOTH
}

type Query{}
type Mutation {}