type Order implements Node{
    id: ID!
    deliveredTo : Customer!
    deliveredBy : Vendor!
    orderStatus: OrderStatus!
    createdAt: DateTime!
    updatedAt: DateTime!
}

type OrderMilk implements Node{
    id: ID!
    milkType : MilkType!
    deliverySession: DeliverySession!
    orderQuantity : BigDecimal!
    pricePerQuantity : BigDecimal!
    createdAt: DateTime!
    updatedAt: DateTime!
}

union User = Customer | Vendor

type Invoice implements Node{
    id: ID!
    user :  User!
    userRole : UserRole!
    amountToPay : BigDecimal!
    amountPaid : BigDecimal!
    totalAmount : BigDecimal!
    paymentStatus : PaymentStatus!
    fromDate : Date!
    toDate : Date!
    createdAt: DateTime!
    updatedAt: DateTime!
}

type OrderEdge{
    node :Order!
    cursor : String!
}

type OrderMilkEdge{
    node : OrderMilk!
    cursor : String!
}

type InvoiceEdge{
    node : Invoice!
    cursor : String!
}

type OrderConnectionResponse{
    edges : [OrderEdge!]!
    pageInfo : PageInfo!
    totalCount :   BigDecimal!
}

type OrderMilkConnectionResponse{
    edges : [OrderMilkEdge!]!
    pageInfo : PageInfo!
    totalCount :   BigDecimal!
}

type InvoiceConnectionResponse{
    edges : [InvoiceEdge!]!
    pageInfo : PageInfo!
    totalCount :   BigDecimal!
}

extend type Query {
    orders(first : Int, after : String,last : Int , before : String , search : Map , filter : [Map] sort : [Map] ):OrderConnectionResponse!
    orderMilks(first : Int, after : String,last : Int , before : String , search : Map , filter : [Map] sort : [Map] ):OrderMilkConnectionResponse!
    invoices(first : Int, after : String,last : Int , before : String , search : Map , filter : [Map] sort : [Map] ):InvoiceConnectionResponse!
    orderByID(id : ID!) :Order!
    orderMilkByID(id : ID!):OrderMilk!
    invoiceByID(id : ID!) : Invoice!
}

input OrderRequest{
    deliveredTo : ID!
    deliveredBy : ID!

}

input OrderMilkRequest{
    order : ID!
    milkType : MilkType!
    deliverySession: DeliverySession!
    orderQuantity : BigDecimal!
}


extend type Mutation {
    saveOrderMilk(orderMilk : OrderRequest!) : OrderMilk!
    generateOrder(customer : ID!) : Order!
    updateOrder(id : ID! , order : OrderRequest!): Order!
    updateOrderMilk (id: ID! , orderMilk : OrderMilkRequest!): OrderMilk!
    updateOrderStatus(id : ID! , status : OrderStatus!): Order!
    generateInvoiceForCustomer(customer : ID!):Invoice!
    generateInvoiceForVendor(vendor : ID!): Invoice!
    updateInvoicePayment(id:ID! , amountPaid : BigDecimal!) : Invoice!
    deleteOrder(id:ID!): ID!
    deleteOrderMilk(id:ID!) :ID!
    deleteInvoice(id:ID!):ID!
}


