enum AccountStatus{
    ACTIVATED, INACTIVATED, SUSPENDED
}

enum UserRole{
    ADMIN, VENDOR, CUSTOMER
}

type User implements Node{
    id: ID!
    username : String!
    contactNumber :String!
    accountStatus : AccountStatus!
    userRole : UserRole!
    createdAt: DateTime!
    updatedAt: DateTime!
}

input UserFilter{
    accountStatus : AccountStatus
    userRole : UserRole
    fromDate : Date
    toDate : Date
}

enum UserSortField{
    USERNAME
    CREATED_AT
}

input userSort{
    order : SortOrder!
    field : UserSortField!
}

type UserEdge{
    cursor : String!
    node : User!
}

type UserConnection{
    edges : [UserEdge!]
    pageInfo : PageInfo
    totalCount : Int
    error : ErrorResponse
}

input UserQuery{
    id : ID
    contactNumber : String
}

type UserResponse{
    user : User
    error : ErrorResponse
}

extend type Query {
    users(
        first : Int
        last : Int
        after : String
        before: String
        filter : UserFilter
        search : String
        sort : userSort
    ): UserConnection!
    user(input : UserQuery):UserResponse!
}


input UpdateUserDetailsInput{
    id : ID!
    username : String
    accountStatus : AccountStatus
}



extend type Mutation {
    deleteUser(input : ID!) : UserResponse!
    updateUserDetails(input : UpdateUserDetailsInput!) :  UserResponse!
}
